actions com pr

diff --git a/.github/workflows/cd-action.yml b/.github/workflows/cd-action.yml
--- a/.github/workflows/cd-action.yml
+++ b/.github/workflows/cd-action.yml
@@ -2,9 +2,9 @@ name: Continuous Deployment
 
 on:
   workflow_dispatch:
-  push:
+  pull_request:
     branches:
-      - production
+      - main
     paths-ignore:
       - .gitignore
       - README.md
@@ -21,7 +21,47 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Executing deploy via SSH
+      - name: testing deploy via ssh
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{secrets.HOST}}
+          username: ${{secrets.USERNAME}}
+          password: ${{secrets.PASS}}
+          script: |
+            BRANCH_NAME=${{ github.head_ref }}
+            UNSTAGGED_IMAGE_ID=$(docker images --filter=reference=site-struct-2024-web:latest --format "{{.ID}}")
+            cd docker_compose_struct/
+            git pull
+            cd site-struct-2024/
+
+            execute_with_retry() {
+              local retries=$1
+              local timeout_duration=$2
+              local command=$3
+              while [ $retries -gt 0 ]; do
+                if timeout $timeout_duration $command; then
+                  echo "==============================================="
+                  echo "$command successful!"
+                  echo "==============================================="
+                  return 0
+                else
+                  echo "==============================================="
+                  echo "$command failed or timed out, retrying..."
+                  echo "==============================================="
+                  ((retries--))
+                fi
+              done
+              echo "==============================================="
+              echo "$command failed or timed out after all retries"
+              echo "==============================================="
+              exit 1
+            }
+
+            execute_with_retry 2 "360s" "BRANCH_NAME=$BRANCH_NAME docker compose build web"
+            execute_with_retry 2 "180s" "docker compose up -d"
+            docker rmi $UNSTAGGED_IMAGE_ID
+
+      - name: executing redeploy via ssh
         uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{secrets.HOST}}
